<?php /**
  * Plugin Name: ZinzinChatBotté
  * Plugin URI: http://localhost/
  * Description: Test.
  * Version: 0.1
  * Author: toto
  * Author URI: http://localhost/
  **/

if (!defined('ABSPATH'))
    exit; // Exit if accessed directly
add_action('wp_head', 'our_pirabaud');

function our_pirabaud()
{

    ?>
    <form>
        <input type="text" placeholder="Parlez à ChatBotté" id="message" name="message">
        <input type="submit" value="Envoyer">
    </form>
    <?php
    global $wpdb;
    $query = $wpdb->prepare("SELECT * FROM chatbot;");
    $rows = $wpdb->get_row($query);

    print_r($rows);

    if (empty($_GET['message'])) {
        echo "<h2>No message</h2>";
    } else {
        $get_message = $_GET['message'];
        $message = "Tu es un chatbot utilisé sur un site internet dédié aux neurosciences. Le site sur lequel tu es sappelle Zenmon Drops. Tu as obligation de rester poli en toute circonstances et faire de ton mieux pour fournir des réponses aux sources fiables. Tu dois toujours vérifier tes informations avant de les communiquer. Tu texprimes dans un langage simple et compréhensible pour une personne non initiée aux neurosciences. Tes réponses doivent être limitées à 300 caractères. Si la question posée ne concerne pas les neurosciences, et uniquement les neurosciences, tu ne dois pas fournir de réponse. Réponds à cette question sauf si elle est n'est pas portée sur les neurosciences : " . $get_message;
        echo "<h2>$get_message</h2>";
  
        $apiKey = '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'; // Replace with your OpenAI API key
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
// $ch = curl_init();

// curl_setopt($ch, CURLOPT_URL, 'https://api.openai.com/v1/chat/completions');
// curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
// curl_setopt($ch, CURLOPT_POST, 1);
// curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n
//     \"model\": \"gpt-3.5-turbo\",\n
//     \"prompt\": \"$message\",\n
//     \"temperature\": 0,\n
//     \"max_tokens\": 300,\n
//     \"top_p\": 1,\n
//     \"frequency_penalty\": 0.0,\n
//     \"presence_penalty\": 0.0,\n
//     \"stop\": [\"0\"]\n}");

// $headers = array();
// $headers[] = 'Content-Type: application/json';
// $headers[] = 'Authorization: Bearer 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';
// curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

// $result = curl_exec($ch);
// if (curl_errno($ch)) {
//     echo 'Error:' . curl_error($ch);
// }
// curl_close($ch);
$model = 'gpt-3.5-turbo';
$header = [
    "Authorization: Bearer " . $apiKey,
    "Content-type: application/json",
];

$temperature = 0.6;
$frequency_penalty = 0;
$presence_penalty= 0;
$prompt = $get_message;
 

$messages = array(
    array(
        "role" => "system",
        "content" => "Tu es le ChatBotté. Tu es un expert en neurosciences. Tu ne peux pas répondre aux questions qui portent sur autre chose que les neurosciences."
        ),
    array(
        "role" => "assistant",
        "content" => "Je suis le ChatBotté. Je suis un expert en neurosciences. Je ne peux pas répondre aux questions qui portent sur autre chose que les neurosciences."
    ),
    array(
        "role" => "user",
        "content" => $prompt
    )
);
//Turbo model
$isTurbo = true;
$url = "https://api.openai.com/v1/chat/completions";
$params = json_encode([
    "messages" => $messages,
    "model" => $model,
    "temperature" => $temperature,
    "max_tokens" => 300,
    "frequency_penalty" => $frequency_penalty,
    "presence_penalty" => $presence_penalty,
    "stream" => false
]);

$curl = curl_init($url);
$options = [
    CURLOPT_POST => true,
    CURLOPT_HTTPHEADER => $header,
    CURLOPT_POSTFIELDS => $params,
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_SSL_VERIFYPEER => false,
    CURLOPT_SSL_VERIFYHOST => 0,
    CURLOPT_WRITEFUNCTION => function($curl, $data) {
        //echo $curl;
        $httpCode = curl_getinfo($curl, CURLINFO_HTTP_CODE);

        if ($httpCode != 200) {
            $r = json_decode($data);
            echo 'data: {"error": "[ERROR]","message":"'.$r->error->message.'"}' . PHP_EOL;
        } else {
            $trimmed_data = trim($data); 
            if ($trimmed_data != '') {
                $response_array = json_decode($trimmed_data, true);
                if ($response_array && $response_array['choices'] && $response_array['choices'][0] && $response_array['choices'][0]['message']) {
                    $content = $response_array['choices'][0]['message']['content'];
                } else {
                    $content = "ERROR";
                }
                echo $content;
                ob_flush();
                flush();
            }
        }
        return strlen($data);
    },
];

curl_setopt_array($curl, $options);
$response = curl_exec($curl);

if ($response === false) {
    echo 'data: {"error": "[ERROR]","message":"'.curl_error($curl).'"}' . PHP_EOL;
}else{

}
        // $wpdb->insert("chatbot", array("id" => NULL, "user_input" => $message, "bot_output" => "toto"));
    }
    ;
}